### ISSUE TITLE
关于React ReactDOM引用问题 

### ISSUE THREAD

**Issue by iT-lijun** [antvis/site#107]
theme/default/src/home/index.jsx：
   import React from 'react'; //导入
   import ReactDOM from 'react-dom';//导入
webpack.config.js： 
 externals: {
    'react-dom': 'ReactDOM',//配置为外部库
    react: 'React',//配置为外部库
    ...
  },
**问题描述：**
 package.json里并没有配置React ReactDOM 依赖
 页面的<script>标签也没有React ReactDOM 引用
 **React ReactDOM到底在哪里？？？？？？？？？**

**Comment by leungwensen** [comment]
React 和 ReactDOM 都是通过 script 标签引入的，这里用的都是全局变量。

https://github.com/antvis/site/blob/master/site/zh-cn/index.html#L35

**Comment by iT-lijun** [comment]
0.吐槽：这命名串，估计连作者都认不出来了吧
1.建议：加点注释吧！！！！！！！！！！！！
2.感谢：Thank @leungwensen a lot for replying
