### ISSUE TITLE
层叠直方图页面，demo的tooltip被遮挡。

### ISSUE THREAD

**Issue by ssthouse** [antvis/site#143]
* **Link**: https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/histogram-stacked.html
* **Platform**: Chrome (macOS)
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/10973821/44265957-506f5f80-a25b-11e8-8715-2af1afe72e7f.png)

似乎是因为图标嵌套在**iframe**里面，导致**tooltip** 超出部分无法显示。

**Comment by leungwensen** [comment]
多谢反馈。其实是因为 tooltip 配置了 inPlot: false 导致的。配置为 true 的话 tooltip 就不会超出画布范围了。
