### ISSUE TITLE
demo (美国各个机场的航线图) 线路显示有错误

### ISSUE THREAD

**Issue by ssthouse** [antvis/site#148]
* **Link**: https://antv.alipay.com/zh-cn/g2/3.x/demo/map/with-connection.html
* **Platform**: Ubuntu Chrome
* **Mini Showcase(like screenshots)**:
![reproduce](https://user-images.githubusercontent.com/10973821/44656737-a8ad1b00-aa2c-11e8-9d69-186abc6d50fc.gif)

- 鼠标没有移动到 **circle** 上时, 也会触发飞行线路的显示. 
- 触发飞行线路的**circle**中心 和 当前鼠标所在**circle**不是同一个.

简单看了一下代码, 还没找到原因 :disappointed:  , 如果不着急修的话可以留给我周末再仔细瞧瞧.

**Comment by ssthouse** [comment]
**问题出现的原因:**

问题似乎出在这个demo中调用的 `view.getSnapRecords` 这个方法, 返回的是离 **x 坐标** 最近的点 
(可以看到上面的动图里面, 鼠标移动时标注的 airport x坐标是和鼠标 ev.x 最近的)
调用逻辑为:
[/src/chart/view.js#L531: getSnapRecords(point)]( https://github.com/antvis/g2/blob/13ac1e3baa0a9691ff3ba39f77e901517a33cfa5/src/chart/view.js#L531)
[/src/geom/mixin/tooltip.js#L181: findPoint(point, dataArray)](https://github.com/antvis/g2/blob/13ac1e3baa0a9691ff3ba39f77e901517a33cfa5/src/geom/mixin/tooltip.js#L181)

看代码发现, 比较最近点的逻辑是 只比较了 **x坐标** : `xScale.translate(item) <= xScale.translate(value)`

同时发现在 `findPoint` 方法中, 对 headMap 进行了特殊的判断: 使用遍历所有点, 比较欧式距离 (x^2 + y^2)的方式 :
[/src/geom/mixin/tooltip.js#L190](https://github.com/antvis/g2/blob/13ac1e3baa0a9691ff3ba39f77e901517a33cfa5/src/geom/mixin/tooltip.js#L190)

如果对本demo使用类似headMap的处理, 问题就可以解决了, 修改后效果如图:
![fixed-result](https://user-images.githubusercontent.com/10973821/45532774-da452500-b827-11e8-9839-ddb4bde50ac7.gif)

**解决方案:**
代码中对于 headMap 的特殊处理是基于  `geom.type` 是 heatmap 的判断 , 但是在用户在非 heatmap中想要得到地图中最近点时, 是没有参数可以控制的, 所以我的想法是给 **getSnapRecords** 和 **findPoint** 加个参数, 用来控制**搜索最近点**的逻辑. 

https://github.com/ssthouse/g2/commit/ad7c928bc4dcec787fa8ebd0328cd896deb413ac

**Comment by dxq613** [comment]
怀疑是 3.0 后面逼近计算的 bug ，看看 2.3 版本的这个 demo 是好的：https://antvis.github.io/g2/demo/10-map/map-bubble.html

@leungwensen 看一下是否是 bug

**Comment by leungwensen** [comment]
老版本逼近计算的逻辑是：对 heatmap / contour / point 都采用欧式距离的。新版可能是删 coutour 的时候把 point 也误删了，我改回来。 @dxq613 @ssthouse

**Comment by leungwensen** [comment]
done 请更新到 3.2.8 修复这个问题
