### ISSUE TITLE
样式 - logo要用给的标准图（图形+文字）

### ISSUE THREAD

**Issue by Jason-Zhangine** [antvis/site#15]
线上：
![image](https://user-images.githubusercontent.com/7369839/33300601-40c49ddc-d42c-11e7-9706-69ac52a0b37b.png)

视觉稿：
![image](https://user-images.githubusercontent.com/7369839/33300642-6ce1ad1a-d42c-11e7-97e7-d8a78776c4f0.png)

**Comment by leungwensen** [comment]
@Jason-Zhangine 可以贴一张 logo 的 SVG 图或者 PNG 图吗？我找不到视觉稿了。。
