### ISSUE TITLE
设计文档配图错误

### ISSUE THREAD

**Issue by greysign** [antvis/site#162]
* **Link**: https://ant.design/docs/spec/feedback-cn
* **Platform**:
* **Mini Showcase(like screenshots)**:
配图错误。2张图片一样。

![image](https://user-images.githubusercontent.com/1445843/47207111-fb67db00-d3bc-11e8-9fe7-06384d23e81a.png)

**Comment by leungwensen** [comment]
你好，这里是蚂蚁金服数据可视化解决方案 AntV 的官网 repo，如果有 AntD（Ant Design） 相关问题需要反馈，可以到他们的 repo 里提 issue。 https://github.com/ant-design/ant-design/
