### ISSUE TITLE
样式 - 左侧导航栏 搜索

### ISSUE THREAD

**Issue by Jason-Zhangine** [antvis/site#20]
现在：
![image](https://user-images.githubusercontent.com/7369839/33302611-7413bebe-d438-11e7-86f5-2ae2f16efa42.png)

改成：
![image](https://user-images.githubusercontent.com/7369839/33302622-894d05d8-d438-11e7-838b-e823a00dd759.png)

**Comment by leungwensen** [comment]
icon 和 placeholder 的字号和颜色具体是啥？ @Jason-Zhangine
