### ISSUE TITLE
[G2 Docs]关于图表的宽度和高度

### ISSUE THREAD

**Issue by jingsam** [antvis/site#27]
API文档中，图表的高度描述如下：
```
width
指定图表的宽度，默认单位为'px'，当 forceFit: true 是宽度不生效。

height
指定图表的高度，默认单位为'px'。
```

有两点疑问：
1. 默认单位为'px'是不是意味着支持其他单位？
2. 经测试，未指定宽高情况下的默认值是500，指出来是不是更好？

另外，padding中说明如下：
```
另外也支持设置百分比，如 padding: [ 20%, 30% ]，该百分比相对于整个图表的宽高。
```

是不是得改为padding: [ '20%', '30%' ]?

**Comment by leungwensen** [comment]
多谢指出！这些问题会在下一次网站迭代上修复掉
