### ISSUE TITLE
[docs] 数据处理fold

### ISSUE THREAD

**Issue by jingsam** [antvis/site#36]
fold意思是折叠，从fold的行为上看，更像是Excel中的转置，叫 transpose会不会更好？

**Comment by leungwensen** [comment]
这个 “折叠” 指的是 ”字段折叠“。从这个数据处理的角度来看，它是 ”把 1 个或者 多个 field 折叠到 key 和 value 两个 field 上“。像 vega 的数据处理模块里也是这么命名的，有个惯例。
