### ISSUE TITLE
样式-整站footer部分

### ISSUE THREAD

**Issue by Jason-Zhangine** [antvis/site#42]
现在整站页面footer规则是乱的（类似）。
整理成：
网站首页、子产品首页是全量的footer；
其他页面一律使用简化footer（只有微博、github、关于我们、版权这一条）

**Comment by leungwensen** [comment]
简化的 footer 是不是都是浅色版本的？ @Jason-Zhangine 

![image](https://user-images.githubusercontent.com/1655789/33642950-543c2546-da77-11e7-8059-d03be8391908.png)

**Comment by Jason-Zhangine** [comment]
就是那个黑色版本的。
![image](https://user-images.githubusercontent.com/7369839/33643160-578e2aea-da78-11e7-8d0e-3740b258b827.png)

**Comment by leungwensen** [comment]
demo 页面应该没有吧？
