### ISSUE TITLE
windows打不开站点

### ISSUE THREAD

**Issue by Tzrong** [antvis/site#76]
```
$cnpm i
$npm run dev
```

访问http://127.0.0.1:2047/zh-cn/index.html，拒绝连接

**Comment by Tzrong** [comment]
环境windows7+chrome

改端口号为9000依然失败

**Comment by leungwensen** [comment]
1. 检查本地防火墙设置
2. 尝试把 127.0.0.1 改为 0.0.0.0

**Comment by Tzrong** [comment]
嗯  按照您的方式 将防火墙关闭并改变相关内容 还是打不开站点 
![image](https://user-images.githubusercontent.com/24354441/35492188-455f5b76-04e6-11e8-91b5-cec9e3c0bd3c.png)

**Comment by leungwensen** [comment]
命令行有什么 log，可以贴一下吗？

**Comment by Tzrong** [comment]
![Uploading image.png…]()

**Comment by Tzrong** [comment]
![image](https://user-images.githubusercontent.com/24354441/35492935-aa9e1924-04ea-11e8-97ac-a0e82514eeac.png)
输出很多  这是最后的部分

**Comment by leungwensen** [comment]
可能是因为 windows 没法并行执行 npm 指令，你这样试试：

开两个命令行，一个运行：

```bash
$ npm run watch
```

另一个运行：

```bash
$ npm run server
```

**Comment by Tzrong** [comment]
![image](https://user-images.githubusercontent.com/24354441/35494516-0956d1ee-04f6-11e8-8cc1-c7b92de778b0.png)

**Comment by leungwensen** [comment]
嗯嗯，那就是也不支持环境变量。那么直接 `npm run server` 改为 `node bin/server.js -d -o`

**Comment by Tzrong** [comment]
还是不可以 
![image](https://user-images.githubusercontent.com/24354441/35494738-a3db92a8-04f7-11e8-8998-a42ebf4d2703.png)

**Comment by Tzrong** [comment]
我又试了一次  可以打开了  谢谢您的耐心解答

**Comment by leungwensen** [comment]
site 的开发确实还没有考虑 windows 环境，等有空会把 windows 支持做好。

**Comment by Cslove** [comment]
Windows系统下照着上面的命令的确打开了。。但是为什么修改文件界面不刷新。。重启服务后内容也不变。。。
改的是theme/default/src/Home/data.js,

**Comment by leungwensen** [comment]
你需要同时开着 `npm run watch` 和 `node bin/server.js -d -o`

**Comment by Cslove** [comment]
嗯 尝试了下 
![_20180130100121](https://user-images.githubusercontent.com/23312535/35544627-5b452ec8-05a6-11e8-8193-d7192f13d221.png)
将server前面的debug等几个命令删了，在同一个命令行窗口运行
npm run watch & npm run server
是可以的~
