### ISSUE TITLE
webpack在监听模式下能否继发启动本地服务

### ISSUE THREAD

**Issue by evildancer** [antvis/site#94]
看到npm scripts中“Dev”下配置的“npm run  watch && npm run  server”甚是不解。如何在在监听模式下继发启动后续的server？

了解到如果是一个express当然是没有问题，可以 使用webpack-dev-middleware中间件来实现功能。但是这里的server.js是简单起了一个服务，就我测试和查到的资料是无法配合使用的。

作为一个强迫症患者想弄明白，还请贵团队指导一下，万分感谢。

**Comment by leungwensen** [comment]
注意，我们的脚本是 `npm run watch & npm run server`， 是命令的“并联”（&），而不是“串联”（&&）。Unix 系的 OS 下，都是可以并行执行的。不过在 windows 下就不一定生效了，需要写一个 node 脚本，用 child_process 来做
