### ISSUE TITLE
npm test 命令失败

### ISSUE THREAD

**Issue by newbienewbie** [antvis/site#96]
你好，我看提交PR的checklist中有要求 npm test ，但是package.json中写的是：
```
"scripts": {
     // ...
    "test": "echo \"Error: no test specified\" && exit 1",
    // ...
}
```
是不是应该修改下？

**Comment by leungwensen** [comment]
目前这个项目还没有需要单测的场景，所以 pre-commit 里只定义里 lint，只需要 `npm run lint` 能通过就行
